# Generated by Django 5.2.16 on 2026-07-28 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='stories.episode')),
            ],
            options={
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('READY', 'Ready')], default='DRAFT', max_length=32)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='production.scene')),
            ],
            options={
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='scene',
            constraint=models.UniqueConstraint(fields=('episode', 'code'), name='unique_scene_code_per_episode'),
        ),
        migrations.AddConstraint(
            model_name='scene',
            constraint=models.UniqueConstraint(fields=('episode', 'order'), name='unique_scene_order_per_episode'),
        ),
        migrations.AddConstraint(
            model_name='shot',
            constraint=models.UniqueConstraint(fields=('scene', 'code'), name='unique_shot_code_per_scene'),
        ),
        migrations.AddConstraint(
            model_name='shot',
            constraint=models.UniqueConstraint(fields=('scene', 'order'), name='unique_shot_order_per_scene'),
        ),
    ]
