# Generated by Django 5.2.16 on 2026-07-28 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_order', models.PositiveIntegerField()),
                ('episode_code', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['episode_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scene_order', models.PositiveIntegerField()),
                ('scene_code', models.CharField(blank=True, max_length=255)),
                ('scene_purpose', models.TextField(blank=True)),
                ('dramatic_objective', models.TextField(blank=True)),
                ('time_context_text', models.TextField(blank=True)),
                ('location_context_text', models.TextField(blank=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenes', to='planning.episode')),
            ],
            options={
                'ordering': ['scene_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shot_order', models.PositiveIntegerField()),
                ('shot_code', models.CharField(blank=True, max_length=255)),
                ('narrative_purpose', models.TextField(blank=True)),
                ('action_intent', models.TextField(blank=True)),
                ('subject_focus', models.TextField(blank=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shots', to='planning.scene')),
            ],
            options={
                'ordering': ['shot_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='planning.project')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodes', to='planning.story'),
        ),
        migrations.CreateModel(
            name='Storyboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storyboards', to='planning.scene')),
            ],
        ),
        migrations.CreateModel(
            name='StoryboardPanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('panel_order', models.PositiveIntegerField()),
                ('panel_notes', models.TextField(blank=True)),
                ('primary_shot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storyboard_panels', to='planning.shot')),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panels', to='planning.storyboard')),
            ],
            options={
                'ordering': ['panel_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='scene',
            constraint=models.UniqueConstraint(fields=('episode', 'scene_order'), name='planning_scene_episode_scene_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='shot',
            constraint=models.UniqueConstraint(fields=('scene', 'shot_order'), name='planning_shot_scene_shot_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('story', 'episode_order'), name='planning_episode_story_episode_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='storyboardpanel',
            constraint=models.UniqueConstraint(fields=('storyboard', 'panel_order'), name='planning_storyboardpanel_storyboard_panel_order_uniq'),
        ),
    ]
