# Generated by Django 5.2.16 on 2026-07-28 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='projects.project')),
            ],
            options={
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField(blank=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='stories.story')),
            ],
            options={
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_story_code_per_project'),
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='unique_story_order_per_project'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('story', 'code'), name='unique_episode_code_per_story'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('story', 'order'), name='unique_episode_order_per_story'),
        ),
    ]
